### ISSUE TITLE
What is the installation password

### ISSUE THREAD

**Issue by tawalan777** [dardizzola/YouTubeDownloaderAllInOne#7]
Hello, the app asked for password during the installation, what is it?

**Comment by dardizzola** [comment]
Is a private fork.


Il giorno mer 28 ago 2024 alle ore 22:59 tawalan777 <
***@***.***> ha scritto:

**Comment by tawalan777** [comment]
Hello, 
![Setup LaMuccaRossaVideoDownloader tmp_bzbx36X2DN](https://github.com/user-attachments/assets/c5f60662-0292-4027-90ba-903a218d35bd)

Below is the app asking for the password, I also attached a screenshot
"Setup.LaMuccaRossaVideoDownloader.exe"

Thanks

**Comment by dardizzola** [comment]
Yes I know.It’s a private fork.Understand?Inviato da mobileIl giorno 29 ago 2024, alle ore 07:47, tawalan777 ***@***.***> ha scritto:﻿
Hello,
Setup.LaMuccaRossaVideoDownloader.tmp_bzbx36X2DN.png (view on web)
Below is the app asking for the password, I also attached a screenshot
"Setup.LaMuccaRossaVideoDownloader.exe"
Thanks

**Comment by tawalan777** [comment]
Hello dear, got it

thanks anyway
